services:
  application:
    build:
      context: .
      target: dev
    restart: no
    command: sh run.sh
    ports:
      - "8080:8080"
      - "5005:5005"
    expose:
      - 8080
    volumes:
      - ./:/app
      - gradle:/home/spring/.gradle

volumes:
  gradle: