services:
  application:
    build:
      context: .
      target: dev
    restart: no
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - ./:/app
      - gradle:/home/spring/.gradle

volumes:
  gradle: